### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ilyalatt** [ilyalatt/Telega#80]
v0.5 (a lot of breaking changes)
- [x] Fixed Updates and Upload
- [x] Simplified union tags
- [x] `IReadOnlyList<T>` instead of `Arr<T>`
- [x] `T?` instead of `Option<T>`
- [x] `NullExtensions` for convenient extensions like `NChoose`
- [x] `LanguageExt` removal
- [x] A lot of new helper methods
- [x] YAML DTO string representation

v0.6 (a lot of breaking changes but mostly fixable by search-and-replace)
- [ ] Start a ping loop by default to keep the updates stream alive
- [ ] Make `Connect` optional
- [ ] Add `Credentials` and default credentials
- [ ] Add `TelegramClientConfig` (credentials, connect config, ping config, custom network stream provider)
- [ ] Use `SafeFiles` for `FileSessionStore`
- [ ] Rename `Upload` to `File` (it is not only for upload purposes)
- [ ] Rename `Match` to `Switch` (to match C# 9 switch)
- [ ] Find a placeholder instead of `Default` to remove `Tag` suffix everywhere
- [ ] Use `ReadOnlyMemory<byte>` instead of `Bytes`? `System.Memory` for `netstandard2.0` or `netstandard2.1` only?

todo
- [ ] Reflection-based YAML instead of generator-based (a lot of unused code bloating the package)?
- [ ] Concurrent download/upload
- [ ] MTProto proxy support
- [ ] `Session` refactoring
